# Site settings
title: Jude Rosario
email: your-email@domain.com
description: "Welcome to my website, you can find stuff about me and ways to get in touch."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ea3a49 #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Bangalore
  - line: India

# Build settings
markdown: kramdown
permalink: pretty
